import pandas as pd
import numpy as np
import difflib
import streamlit as st
import os
from scripts.qwerty_mapper import classify_typo

# =====================================================================
# MODULE: typo_behavior_loader.py (The Model / Backend)
# Strict Decoupling: No Streamlit UI rendering commands (st.write, etc.) 
# are permitted in this file. 
# =====================================================================

# ---------------------------------------------------------------------
# PHASE 1: DATA INGESTION & SCHEMA UNIFICATION
# ---------------------------------------------------------------------

# 1: aalto data loader
# ---------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_aalto(base_dir):
    """ Loads the FULL, pre-processed Aalto dataset generated by the GitHub ETL pipeline. """
    # We load the mathematically finished file, not the raw one
    processed_path = os.path.join(base_dir, 'aalto_processed.parquet')
    
    if os.path.exists(processed_path):
        df_aalto = pd.read_parquet(processed_path)
        return df_aalto
    else:
        # Failsafe: if the processed file isn't built yet, try loading the raw one
        raw_path = os.path.join(base_dir, 'aalto_macro.parquet')
        if os.path.exists(raw_path):
             return pd.read_parquet(raw_path)
        return pd.DataFrame()

# 2: keyrecs data loader
# ---------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_keyrecs(base_dir):
    """ Loads KeyRecs Digraph data. Cannot be used for word reconstruction. """
    filepath = os.path.join(base_dir, 'keyrecs_micro.parquet')
    
    if not os.path.exists(filepath):
        return pd.DataFrame()

    try:
        df = pd.read_parquet(filepath)
    except Exception as e:
        st.error(f"⚠️ KeyRecs Parquet Corrupted. Please re-download from Colab.")
        return pd.DataFrame()

    # Rename to match Master Schema where possible
    # In this dataset, DU.key1.key1 = Dwell Time, DD.key1.key2 = Flight Time
    df = df.rename(columns={
        'participant': 'User_ID',
        'key1': 'Key_Char',
        'DU.key1.key1': 'Dwell_Time',
        'DD.key1.key2': 'Flight_Time'
    })

    df['Dataset'] = 'KeyRecs'
    df['Device_Type'] = 'desktop' 
    df['Task_Type'] = 'free_text'
    df['User_ID'] = df['User_ID'].fillna('Unknown_User').astype(str)
    df['Session_ID'] = df['Dataset'] + '_' + df['User_ID']
    if 'Key_Char' not in df.columns:
        df['Key_Char'] = np.nan

    # Convert seconds to milliseconds for our standard
    if 'Dwell_Time' in df.columns:
        df['Dwell_Time'] = df['Dwell_Time'] * 1000
    if 'Flight_Time' in df.columns:
        df['Flight_Time'] = df['Flight_Time'] * 1000

    # Fill Missing/Static Categorical Data
    df['Dataset'] = 'KeyRecs'
    df['Device_Type'] = 'desktop' 
    df['Task_Type'] = 'free_text'
    df['User_ID'] = df['User_ID'].fillna('Unknown_User').astype(str)
    df['Session_ID'] = df['Dataset'] + '_' + df['User_ID']
    df['Key_Code'] = -1
    df['Timestamp_Press'] = 0.0
    df['Timestamp_Release'] = df['Dwell_Time']
    df['Delta_Milliseconds'] = 0.0

    # Initialize Phase 2 Placeholder Columns (Will remain empty)
    df['Intended_Char'] = np.nan
    df['Typed_Char'] = np.nan
    df['Is_Typo'] = False

    master_cols = [
        'Dataset', 'Session_ID', 'User_ID', 'Device_Type', 'Task_Type', 
        'Key_Code', 'Key_Char', 'Timestamp_Press', 'Timestamp_Release', 
        'Delta_Milliseconds', 'Dwell_Time', 'Flight_Time', 
        'Intended_Char', 'Typed_Char', 'Is_Typo'
    ]
    
    # Only return columns that successfully mapped
    available_cols = [col for col in master_cols if col in df.columns]
    return df[available_cols]

# 3: CMU data loader
# ---------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_cmu(base_dir):
    """ Loads CMU Benchmark. Melts password repetitions into single keystrokes. """
    # Explicitly target the file itself
    filepath = os.path.join(base_dir, 'cmu_baseline.parquet')
    
    if os.path.exists(filepath):
        df = pd.read_parquet(filepath)
        return df
    else:
        return pd.DataFrame()

    # INCORRECT: This tells PyArrow to read the entire documents folder
    filepath = base_dir 
    df = pd.read_parquet(filepath)
    
    # 1. Define the password sequence used in the CMU dataset
    password_chars = ['.', 't', 'i', 'e', '5', 'R', 'o', 'a', 'n', 'l', 'Enter']
    
    records = []
    
    # CMU data is structured wide (1 row = 1 password attempt). 
    # We must melt it to long (1 row = 1 keystroke) to match our event-based schema.
    for _, row in df.iterrows():
        user = str(row.get('subject', 'Unknown'))
        session = f"CMU_{user}_S{row.get('sessionIndex', 1)}_R{row.get('rep', 1)}"
        
        # We simulate a timeline starting at T=0 for each repetition
        current_time = 0.0
        
        # CMU column naming convention: H.key (Hold/Dwell), DD.key1.key2 (Down-Down/Flight)
        for i, char in enumerate(password_chars):
            # Dwell time
            dwell_col = f"H.{char}" if char != '5' else "H.five"
            dwell_col = "H.Shift.r" if char == 'R' else dwell_col
            dwell = row.get(dwell_col, 0.1) * 1000  # Convert seconds to ms
            
            # Flight time (from previous key)
            flight = 0.0
            if i > 0:
                prev_char = password_chars[i-1]
                # Simplify naming lookup for demonstration
                flight = 0.2 * 1000 # Placeholder baseline for CMU flight conversion
                
            current_time += flight
            
            records.append({
                'Dataset': 'CMU',
                'Session_ID': session,
                'User_ID': user,
                'Device_Type': 'desktop',
                'Task_Type': 'password',
                'Key_Code': -1, # CMU doesn't provide explicit browser keycodes
                'Key_Char': char,
                'Timestamp_Press': current_time,
                'Timestamp_Release': current_time + dwell,
                'Delta_Milliseconds': current_time,
                'Dwell_Time': dwell,
                'Flight_Time': flight,
                'Intended_Char': char,
                'Typed_Char': char,
                'Is_Typo': False
            })
            
    master_df = pd.DataFrame(records)
    return master_df

# 4: Clarkson data loader
# ---------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_clarkson(base_dir):
    """ Loads the pre-merged, mathematically finalized Clarkson Dataset. """
    filepath = os.path.join(base_dir, 'clarkson_processed.parquet')
    
    if os.path.exists(filepath):
        return pd.read_parquet(filepath)
    else:
        # Failsafe
        return pd.DataFrame()

# 5: Call and cache our four functions
# ---------------------------------------------------------------------
@st.cache_data(show_spinner="Loading optimized Parquet chunks into RAM...")
def load_all_datasets():
    """
    Loads the highly compressed Parquet files generated in Colab.
    MATLAB Analogy: Pre-allocating and loading data once at the start of 
    a script so loops don't constantly hit the hard drive.
    """
    # Define paths to the 'documents/' folder
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'documents'))
    
    # Check if files exist (prevents crash if Colab step hasn't been completed for all files yet)
    if not os.path.exists(os.path.join(base_dir, 'keyrecs_micro.parquet')):
        st.error("Data files missing from documents/ directory. Please run Phase 0 in Colab first.")
        return None, None, None, None
        
    # --- Apply Phase 1A Loading the Data ---
    df_cmu = load_cmu(base_dir)
    df_keyrecs = load_keyrecs(base_dir)
    df_clarkson = load_clarkson(base_dir)
    df_aalto = load_aalto(base_dir)

    # --- Apply Phase 1B Typo Detection (Backspace Footprints) ---
    # KeyRecs remains excluded as it is a macro-digraph dataset.
    df_clarkson = apply_typo_taxonomy(df_clarkson)
    
    # --- Apply Phase 1C Word Boundaries ---
    df_clarkson = build_word_boundaries(df_clarkson)
    
    # --- Apply Phase 1C Levenshtein Anomaly Detection ---
    df_clarkson = flag_levenshtein_anomalies(df_clarkson)
    
    # --- Apply Phase 1C Historical Consistency Filter ---
    df_clarkson = apply_historical_consistency_filter(df_clarkson)

    df_cmu = calculate_muscle_memory_decay(df_cmu)

    return df_cmu, df_keyrecs, df_aalto, df_clarkson

# ---------------------------------------------------------------------
# PHASE 1B: TYPO DETECTION ALGORITHMS
# ---------------------------------------------------------------------
def apply_typo_taxonomy(df):
    """Categorizes errors using the QWERTY distance and cognitive maps."""
    # Check if this specific dataset even supports typo tracking
    if 'Intended_Char' not in df.columns or 'Typed_Char' not in df.columns:
        df['Typo_Category'] = 'Not Applicable'
        return df

    # Apply taxonomy only where an intended character exists
    df['Typo_Category'] = df.apply(
        lambda row: classify_typo(row['Intended_Char'], row['Typed_Char']) 
        if pd.notnull(row['Intended_Char']) and row['Intended_Char'] != row['Typed_Char']
        else 'Correct', 
        axis=1
    )
    return df

# ---------------------------------------------------------------------
# PHASE 1C: WORD RECONSTRUCTION & HISTORICAL CONSISTENCY
# ---------------------------------------------------------------------

def build_word_boundaries(df):
    """Increments Word_ID every time a Space or Enter is detected."""
    if 'Timestamp_ms' not in df.columns:
        return df

    # Sort to ensure we aren't mixing up different users' timelines
    df = df.sort_values(['Participant_ID', 'Timestamp_ms'])
    
    # 32 = Space, 13 = Enter (Standard JS/Browser Keycodes)
    df['is_delimiter'] = df['Key_Code'].isin([32, 13])
    
    # Cumulative sum creates a unique ID for every word in a session
    df['Word_ID'] = df.groupby('Participant_ID')['is_delimiter'].cumsum().shift(1).fillna(0).astype(int)
    
    return df.drop(columns=['is_delimiter'])

def flag_levenshtein_anomalies(df, dictionary_fallback=None):
    """
    Reconstructs keystrokes into words and uses Sequence Alignment 
    to find Uncorrected Typos (Category A, B, C) that lack a Backspace footprint.
    """
    if df is None or df.empty or 'Word_ID' not in df.columns:
        return df

    # 1. Reconstruct the Typed Word for each Word_ID block
    # We drop NaNs (like Shift keys) and join the characters into a single string
    reconstructed = df.dropna(subset=['Key_Char']).groupby(['Session_ID', 'Word_ID'])['Key_Char'].apply(lambda x: ''.join(x.astype(str))).reset_index()
    reconstructed = reconstructed.rename(columns={'Key_Char': 'Submitted_Word'})

    # 2. Identify the Expected Word
    # Note: For Transcription tasks, you will map the prompt text here.
    # For Free Text, we assume 'dictionary_fallback' is a spellcheck lookup.
    # For now, we will create a placeholder 'Expected_Word' column to build the architecture.
    reconstructed['Expected_Word'] = reconstructed['Submitted_Word'] # Placeholder: replace with actual expected text logic later

    # 3. Calculate Sequence Alignment for mismatches
    mismatch_mask = reconstructed['Expected_Word'] != reconstructed['Submitted_Word']
    mismatches = reconstructed[mismatch_mask].copy()

    # 4. Find the exact character index of the typo using difflib
    error_records = []
    for _, row in mismatches.iterrows():
        expected = row['Expected_Word']
        submitted = row['Submitted_Word']
        
        # SequenceMatcher finds the exact diff operations
        matcher = difflib.SequenceMatcher(None, expected, submitted)
        for tag, i1, i2, j1, j2 in matcher.get_opcodes():
            if tag in ('replace', 'insert', 'delete'):
                error_records.append({
                    'Session_ID': row['Session_ID'],
                    'Word_ID': row['Word_ID'],
                    'Typo_Index': j1, # The index in the submitted string
                    'Intended_Char': expected[i1:i2] if tag != 'insert' else '',
                    'Typed_Char': submitted[j1:j2] if tag != 'delete' else ''
                })

    # 5. Map the errors back to the original microscopic keystroke DataFrame
    if error_records:
        error_df = pd.DataFrame(error_records)
        
        # We merge based on Session, Word_ID, and use cumcount to match the character index
        df['Char_Index'] = df.groupby(['Session_ID', 'Word_ID']).cumcount()
        
        df = pd.merge(df, error_df, left_on=['Session_ID', 'Word_ID', 'Char_Index'], right_on=['Session_ID', 'Word_ID', 'Typo_Index'], how='left')
        
        # Update the master columns
        new_errors = df['Typo_Index'].notna()
        df.loc[new_errors, 'Is_Typo'] = True
        # Coalesce the intended/typed chars so we don't overwrite Backspace footprints
        df['Intended_Char'] = df['Intended_Char_y'].combine_first(df['Intended_Char_x'])
        df['Typed_Char'] = df['Typed_Char_y'].combine_first(df['Typed_Char_x'])
        
        # Drop temporary merge columns
        df = df.drop(columns=['Char_Index', 'Typo_Index', 'Intended_Char_x', 'Intended_Char_y', 'Typed_Char_x', 'Typed_Char_y'])

    return df

def apply_historical_consistency_filter(df, consistency_threshold=0.8):
    """
    Identifies 'Recall Errors' (Misspellings) vs 'Motor Errors' (Typos).
    If a user makes the exact same error for a specific word > 80% of the time,
    it is flagged as a competence error so the ML model can ignore it.
    """
    if df is None or df.empty or 'Word_ID' not in df.columns:
        return df

    # 1. Reconstruct words to evaluate consistency
    words_df = df.dropna(subset=['Key_Char']).groupby(['User_ID', 'Session_ID', 'Word_ID'])['Key_Char'].apply(lambda x: ''.join(x.astype(str))).reset_index()
    words_df = words_df.rename(columns={'Key_Char': 'Submitted_Word'})
    
    # Placeholder for the prompt text (Expected_Word)
    words_df['Expected_Word'] = words_df['Submitted_Word'] 

    # 2. Count how many times the user made a specific exact error
    error_counts = words_df.groupby(['User_ID', 'Expected_Word', 'Submitted_Word']).size().reset_index(name='Specific_Error_Count')

    # 3. Count total times the user attempted the intended word
    total_attempts = words_df.groupby(['User_ID', 'Expected_Word']).size().reset_index(name='Total_Attempts')

    # 4. Merge to calculate the ratio
    consistency_df = pd.merge(error_counts, total_attempts, on=['User_ID', 'Expected_Word'])
    consistency_df['Error_Ratio'] = consistency_df['Specific_Error_Count'] / consistency_df['Total_Attempts']

    # 5. Create the filter mask (True = Consistent Misspelling/Recall Error)
    # We only care if it's actually a mismatch. If Expected == Submitted, it's not an error.
    consistency_df['Is_Recall_Error'] = (consistency_df['Expected_Word'] != consistency_df['Submitted_Word']) & (consistency_df['Error_Ratio'] >= consistency_threshold)
    
    # 6. Merge the flag back into the word dataframe, then back to the microscopic keystrokes
    words_df = pd.merge(words_df, consistency_df[['User_ID', 'Expected_Word', 'Submitted_Word', 'Is_Recall_Error']], on=['User_ID', 'Expected_Word', 'Submitted_Word'], how='left')
    
    df = pd.merge(df, words_df[['Session_ID', 'Word_ID', 'Is_Recall_Error']], on=['Session_ID', 'Word_ID'], how='left')
    
    # Clean up NaNs
    df['Is_Recall_Error'] = df['Is_Recall_Error'].fillna(False)

    return df

def calculate_raw_digraphs(df):
    """
    Calculates Hold and Flight times for Raw Sequential datasets.
    This allows Aalto/Clarkson to be analyzed alongside CMU/KeyRecs.
    """
    if 'Timestamp_ms' not in df.columns or 'Action_Type' not in df.columns:
        return df
    
    # Ensure temporal integrity within each user session
    df = df.sort_values(['Participant_ID', 'Timestamp_ms'])
    
    # 1. Calculate Flight Time (Down-to-Down)
    # The time difference between the current PRESS and the previous PRESS
    press_mask = df['Action_Type'] == 'PRESS'
    df.loc[press_mask, 'Flight_DD_ms'] = df[press_mask].groupby('Participant_ID')['Timestamp_ms'].diff()
    
    # 2. Calculate Hold Time (Dwell Time)
    # For datasets like Clarkson II where Press and Release are separate rows
    # we find the time difference between a PRESS and the NEXT event for that same user
    df['Hold_Time_ms'] = df.groupby(['Participant_ID', 'Key_Code'])['Timestamp_ms'].diff()
    # Note: We only keep Hold times on 'RELEASE' rows
    df.loc[df['Action_Type'] == 'PRESS', 'Hold_Time_ms'] = np.nan
    
    return df

# ---------------------------------------------------------------------
# PHASE 2: MACRO-LEVEL BENCHMARKING
# ---------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def calculate_muscle_memory_decay(df_cmu):
    """ 
    Calculates the universal muscle memory decay curve from the CMU dataset.
    Averages flight times across all users to find the steady-state latency.
    """
    if df_cmu is None or df_cmu.empty:
        return pd.DataFrame()

    # 1. Isolate the Flight Time columns
    dd_cols = [col for col in df_cmu.columns if col.startswith('DD.')]
    
    if not dd_cols:
        return pd.DataFrame()

    # 2. Calculate the average flight time for the entire password attempt
    # MATLAB Analogy: mean(matrix, 2) to get the row-wise average
    df_cmu['Avg_Flight_Time'] = df_cmu[dd_cols].mean(axis=1)

    # 3. Create a continuous X-Axis (Attempt Number 1 through 400)
    # CMU users did 8 sessions of 50 reps. 
    if 'sessionIndex' in df_cmu.columns and 'rep' in df_cmu.columns:
        df_cmu['Attempt_Number'] = ((df_cmu['sessionIndex'] - 1) * 50) + df_cmu['rep']
    else:
        # Fallback just in case the column names vary slightly
        df_cmu['Attempt_Number'] = df_cmu.groupby('subject').cumcount() + 1

    # 4. Collapse the 51 users into a single, universal average line
    decay_curve = df_cmu.groupby('Attempt_Number')['Avg_Flight_Time'].mean().reset_index()

    return decay_curve

# ---------------------------------------------------------------------
# PHASE 3 & 4: TAXONOMY & FEATURE ENGINEERING
# ---------------------------------------------------------------------
def engineer_behavioral_features(df_micro):
    """ 
    Calculates Dwell/Flight latencies and Rolling Variance (Burstiness).
    """
    # 3. Synthesize missing digraphs for raw data
    df_micro = calculate_raw_digraphs(df_micro)
    
    # 4. Calculate Rolling WPM (Phase 4 Cognitive Load Metric)
    # Using 10-event windows to track bursts in speed
    if 'Flight_DD_ms' in df_micro.columns:
        df_micro['Rolling_IKI'] = df_micro.groupby('Participant_ID')['Flight_DD_ms'].transform(
            lambda x: x.rolling(window=10, min_periods=1).mean()
        )
        
    return df_micro

# ---------------------------------------------------------------------
# PHASE 5: MACHINE LEARNING (SINGLETON INSTANCE)
# ---------------------------------------------------------------------
@st.cache_resource
def load_ml_pipeline():
    """
    Caches the Scikit-Learn Random Forest model to prevent UI lag.
    MATLAB Analogy: Compiling a function to a .mex file to bypass interpreter overhead.
    """
    # TODO: Train or load the SMOTE-balanced ML model
    model = None 
    return model
