# =====================================================================
# FILE: scripts/tech_in_ed_etl.py (Formerly run_etl.py)
# PURPOSE: Unifies the macro datasets generated by Google Colab into 
# a single master schema optimized for the Streamlit Hub.
# =====================================================================
import pandas as pd
import numpy as np
import os
import sys

print("🚀 Starting EdTech Master ETL Pipeline...")

# --- STRICT DIRECTORY & PATH CONFIGURATION ---
# MATLAB Bridge: Setting the Current Working Directory paths dynamically.
# This ensures it works on your local machine, GitHub Actions, and DigitalOcean.
base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'documents'))

# Define Input Paths (Generated from Phase 0 Colab Script)
pisa_source = os.path.join(base_dir, 'PISA_macro.parquet')
wbes_source = os.path.join(base_dir, 'WBES_macro.parquet')

# Define Output Path
master_output = os.path.join(base_dir, 'master_dataset.parquet')

# ---------------------------------------------------------
# PHASE 1: LOAD MACRO DATASETS
# ---------------------------------------------------------
print("📥 Loading Parquet Sources...")
if not os.path.exists(pisa_source) or not os.path.exists(wbes_source):
    print("❌ ERROR: Source parquet files not found in the 'documents' folder.")
    print(f"👉 Ensure both '{pisa_source}' and '{wbes_source}' have been downloaded from Colab.")
    sys.exit(1)

df_pisa = pd.read_parquet(pisa_source)
df_wbes = pd.read_parquet(wbes_source)

# 1. Schema Standardization (Rename if they exist)
if 'Tech_Usage' in df_pisa.columns:
    df_pisa = df_pisa.rename(columns={'Tech_Usage': 'Curriculum_Complexity_Index'})
if 'Math_Score' in df_pisa.columns:
    df_pisa = df_pisa.rename(columns={'Math_Score': 'Learning_Efficiency_Score'})

# 2. 🛡️ THE GRACEFUL FALLBACK: 
# If the Kaggle dataset was missing the specific ICT column codes, 
# synthesize the proxy metrics so the portfolio UI remains functional.
np.random.seed(42) # Ensures the proxy data looks the exact same every time
if 'Curriculum_Complexity_Index' not in df_pisa.columns:
    print("⚠️ 'Tech_Usage' missing from Kaggle data. Injecting proxy Complexity Index...")
    # Creates a baseline of 40 that grows linearly over time + random noise
    df_pisa['Curriculum_Complexity_Index'] = (
        40 + ((df_pisa['Year'] - 1990) * 1.5) + np.random.normal(0, 3, len(df_pisa))
    ).astype('float32')

if 'Learning_Efficiency_Score' not in df_pisa.columns:
    print("⚠️ 'Math_Score' missing from Kaggle data. Injecting proxy Efficiency Score...")
    # Creates a baseline of 50 that grows logarithmically over time
    df_pisa['Learning_Efficiency_Score'] = (
        50 + (10 * np.log1p(df_pisa['Year'] - 1990)) + np.random.normal(0, 2, len(df_pisa))
    ).astype('float32')

# ---------------------------------------------------------
# PHASE 2: MERGE AND ALIGNMENT (Inner Join)
# ---------------------------------------------------------
print("🔄 Merging into Master Schema...")
# MATLAB Bridge: Equivalent to innerjoin(df_wbes, df_pisa, 'Keys', {'Country', 'Year'})
df_master = pd.merge(df_wbes, df_pisa, on=['Country', 'Year'], how='inner')

# Sort chronologically by Country, then Year
df_master = df_master.sort_values(by=['Country', 'Year'])

# Handling missing data across specific years (Forward-fill, then Back-fill)
# This prevents broken line charts in Plotly if a country skipped a testing year.
df_master = df_master.groupby('Country').ffill().bfill().reset_index()

# ---------------------------------------------------------
# PHASE 3: AGGRESSIVE DOWNCASTING & SANITIZATION
# ---------------------------------------------------------
print("📉 Sanitizing Types for PyArrow & Streamlit...")

# Ensure Country is a clean string (No mixed types)
if 'Country' in df_master.columns:
    df_master['Country'] = df_master['Country'].astype(str)

# Downcast numerics
for col in df_master.columns:
    if col == 'Country':
        continue
    
    # Coerce any weird artifacts into numerics, forcing NaN if invalid
    df_master[col] = pd.to_numeric(df_master[col], errors='coerce')
    
    if df_master[col].dtype == 'float64':
        df_master[col] = df_master[col].astype('float32')
    elif df_master[col].dtype == 'int64':
        df_master[col] = pd.to_numeric(df_master[col], downcast='integer')

# Drop any rows where critical join keys somehow became NaN
df_master = df_master.dropna(subset=['Country', 'Year'])

# ---------------------------------------------------------
# PHASE 4: EXPORT
# ---------------------------------------------------------
df_master.to_parquet(master_output, engine='fastparquet', index=False)

print(f"✅ Master ETL Complete! Target Schema built with {len(df_master)} rows.")
print(f"💾 Deployed strictly to: {master_output}")